AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'repalce me in repo secrets'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
